### ISSUE TITLE
Exception with Java 17 when signing a message with keyReferenceType="Identifier"

### ISSUE THREAD

**Issue by sephiroth-j** [eclipse-ee4j/metro-wsit#130]
Signing a message with X509Token keyReferenceType="Identifier" fails with the following exception.

keyReferenceType="IssuerSerialNumber" is fine as well as keyReferenceType="Direct".

This is likely caused by [JEP 403](https://openjdk.java.net/jeps/403).

wssx-impl Version 2.4.6

**Error**
```
java.lang.IllegalAccessError: class com.sun.wsit.security.SunKeyIdentifierSPI (in unnamed module @0x6737fd8f) cannot access class sun.security.util.DerValue (in module java.base) because module java.base does not export sun.security.util to unnamed module @0x6737fd8f
	at com.sun.wsit.security.SunKeyIdentifierSPI.getSubjectKeyIdentifier(SunKeyIdentifierSPI.java:34)
	at com.sun.xml.wss.core.reference.X509SubjectKeyIdentifier.getSubjectKeyIdentifier(X509SubjectKeyIdentifier.java:83)
	at com.sun.xml.wss.impl.keyinfo.KeyIdentifierStrategy.getKeyIdentifier(KeyIdentifierStrategy.java:134)
	at com.sun.xml.wss.impl.keyinfo.KeyIdentifierStrategy.insertKey(KeyIdentifierStrategy.java:87)
	at com.sun.xml.wss.impl.dsig.SignatureProcessor.handleX509Binding(SignatureProcessor.java:1968)
	at com.sun.xml.wss.impl.dsig.SignatureProcessor.sign(SignatureProcessor.java:411)
	at com.sun.xml.wss.impl.filter.SignatureFilter.sign(SignatureFilter.java:621)
	at com.sun.xml.wss.impl.filter.SignatureFilter.process(SignatureFilter.java:578)
	at com.sun.xml.wss.impl.HarnessUtil.processWSSPolicy(HarnessUtil.java:69)
	at com.sun.xml.wss.impl.HarnessUtil.processDeep(HarnessUtil.java:248)
	at com.sun.xml.wss.impl.SecurityAnnotator.processMessagePolicy(SecurityAnnotator.java:164)
	at com.sun.xml.wss.impl.SecurityAnnotator.secureMessage(SecurityAnnotator.java:125)
	at com.sun.xml.wss.impl.misc.XWSSProcessor2_0Impl.secureOutboundMessage(XWSSProcessor2_0Impl.java:82)
```

https://github.com/eclipse-ee4j/metro-wsit/blob/378dd0b6ba8e5977b81a96af66a2f7713897e3bf/wsit/ws-sx/wssx-impl/src/main/java/com/sun/wsit/security/SunKeyIdentifierSPI.java#L34

**Java version**
```
❯ java -version
java version "17" 2021-09-14 LTS
Java(TM) SE Runtime Environment (build 17+35-LTS-2724)
Java HotSpot(TM) 64-Bit Server VM (build 17+35-LTS-2724, mixed mode, sharing)
```

**Comment by sephiroth-j** [comment]
So, there are four references of "sun.security" in the java code of metro-wsit. Okay, just three because one is a string value.
https://github.com/eclipse-ee4j/metro-wsit/search?l=Java&q=sun.security.

Two of them are used to retrieve the subjectKeyIdentifier from a X509Certificate.
https://github.com/eclipse-ee4j/metro-wsit/blob/378dd0b6ba8e5977b81a96af66a2f7713897e3bf/wsit/ws-sx/wssx-impl/src/main/java/com/sun/wsit/security/SunKeyIdentifierSPI.java#L34
https://github.com/eclipse-ee4j/metro-wsit/blob/378dd0b6ba8e5977b81a96af66a2f7713897e3bf/wsit/ws-sx/wssx-impl/src/test/java/com/sun/xml/wss/callback/PolicyCallbackHandler1.java#L576

This can be achieved using the following extraction method. This is of course simplified but it is sufficient for subjectKeyIdentifier.

```java
class Foo
{
	byte[] getSubjectKeyIdentifier(X509Certificate cert) throws Exception
	{
		byte[] rawExtValue = cert.getExtensionValue(SUBJECT_KEY_IDENTIFIER_OID);
		byte[] extValue = extractDERValue(rawExtValue);
		return extValue;
	}

	/**
	 * total header length
	 */
	private static final byte HEADER_LENGTH = 4;

	/**
	 * length of a header value
	 */
	private static final byte HEADER_FIELD_LENGTH = 1;

	/**
	 * position (0-based) of the header field that contains the expected length of the actual value in byte
	 */
	private static final byte HEADER_FIELD_VALUE_LENGTH = 3;

	/**
	 * return the actual value of an x.509 extension
	 *
	 * @param rawExtensionValue raw value from {@link X509Extension#getExtensionValue(java.lang.String)
	 * @return the actual value
	 */
	private static byte[] extractDERValue(final byte[] rawExtensionValue)
	{
		if (rawExtensionValue.length < HEADER_LENGTH)
		{
			throw new IllegalArgumentException("rawExtensionValue to short, header is missing");
		}

		final int valueLength = (new BigInteger(Arrays.copyOfRange(rawExtensionValue, HEADER_FIELD_VALUE_LENGTH, HEADER_FIELD_VALUE_LENGTH + HEADER_FIELD_LENGTH))).intValue();
		final int expectedTotalLength = HEADER_LENGTH + valueLength;
		if (rawExtensionValue.length < expectedTotalLength)
		{
			throw new IllegalArgumentException(String.format("rawExtensionValue to short (expected=%d, actual=%d)", expectedTotalLength, rawExtensionValue.length));
		}
		else if (rawExtensionValue.length > expectedTotalLength)
		{
			throw new IllegalArgumentException(String.format("rawExtensionValue to big (expected=%d, actual=%d)", expectedTotalLength, rawExtensionValue.length));
		}
		return Arrays.copyOfRange(rawExtensionValue, HEADER_LENGTH, HEADER_LENGTH + valueLength);
	}
}

**Comment by sephiroth-j** [comment]
[KerberosLogin.java](https://github.com/eclipse-ee4j/metro-wsit/blob/378dd0b6ba8e5977b81a96af66a2f7713897e3bf/wsit/ws-sx/wssx-impl/src/main/java/com/sun/xml/ws/security/impl/kerberos/KerberosLogin.java) is not affected, the package `com.sun.security` can still be used without `--add-opens`. Same for [KeyIdentifierSPI.java](https://github.com/eclipse-ee4j/metro-wsit/blob/378dd0b6ba8e5977b81a96af66a2f7713897e3bf/wsit/ws-sx/wssx-impl/src/main/java/com/sun/xml/wss/core/reference/KeyIdentifierSPI.java), the tests using the classloader are working without `--add-opens`.

**Comment by lukasj** [comment]
Thanks!
