### ISSUE TITLE
webservices-osgi-2.4.3 class not found com/sun/org/apache/xml/internal/resolver/CatalogManager

### ISSUE THREAD

**Issue by malm66** [eclipse-ee4j/metro-wsit#54]
When trying to use webservices-osgi-2.4.3 in an Eclipse RCP application under Java 11 I get the  following NoClassDefFoundError:

Caused by: java.lang.NoClassDefFoundError: com/sun/org/apache/xml/internal/resolver/CatalogManager
	at com.sun.xml.ws.util.xml.XmlUtil.createDefaultCatalogResolver(XmlUtil.java:296)
	at com.sun.xml.ws.client.WSServiceDelegate.createCatalogResolver(WSServiceDelegate.java:348)
	at com.sun.xml.ws.client.WSServiceDelegate.parseWSDL(WSServiceDelegate.java:334)
	at com.sun.xml.ws.client.WSServiceDelegate.<init>(WSServiceDelegate.java:292)
	at com.sun.xml.ws.client.WSServiceDelegate.<init>(WSServiceDelegate.java:201)
	at com.sun.xml.ws.client.WSServiceDelegate.<init>(WSServiceDelegate.java:182)
	at com.sun.xml.ws.client.WSServiceDelegate.<init>(WSServiceDelegate.java:178)
	at com.sun.xml.ws.spi.ProviderImpl.createServiceDelegate(ProviderImpl.java:89)
	at javax.xml.ws.Service.<init>(Service.java:82)
	at au.net.synergy.wts.server.ws.client.management.ServerManagerImplService.<init>(ServerManagerImplService.java:47)

This class has been removed from the JDK since Java 10 but is referenced by com.sun.xml.ws.util.xml.XmlUtil. 

How can I make this work?

**Comment by lukasj** [comment]
should be fixed now through ee6eb40 (master) and f76ab70 (EE8)
